#!/bin/sh

# Extract the type of a bibtex record

PrintUsage() {
    cat << EOF
Usage: $(basename $0) <doi>

Extract the type from a bibtex entry

The bibtex can be provided as an argument or via stdin. Command line arguments
take precendence over data piped in.
EOF
}

record="$1"
if [ -z "$record" ]; then
    [ ! -t 0 ] && record=$(</dev/stdin)
    [ -z "$record" ] && PrintUsage && exit 1
fi

echo "$record" |\
    grep -E '^@.+{.*,' |\
    cut -d '{' -f 1 |\
    cut -d '@' -f 2 |\
    sed 's/^\s*//' |\
    sed 's/\s*$//'
