#!/bin/sh

# Extract the key from a bibtex entry

PrintUsage() {
    cat << EOF
Usage: $(basename $0) <bibtex>

Extract the key from a bibtex entry

The bibtex can be provided as an argument or via stdin. Command line arguments
take precendence over data piped in.
EOF
}

record="$1"
if [ -z "$record" ]; then
    [ ! -t 0 ] && record=$(</dev/stdin)
    [ -z "$record" ] && PrintUsage && exit 1
fi

echo "$record" |\
    grep -E '^@.+{.*,' |\
    sed -E 's/^@.+\{\s*//' |\
    sed -E 's/\s*,.*//'
