#!/bin/sh

# Add multiple files to the database (with unknown database entries)

PrintUsage() {
    cat 1>&2 << EOF
Usage: $(basename $0) <options> <files>

Add multiple files to the database without the associated bibliographic
information.

Options:
  -d : delete the original file after copying
EOF
}

##### MAIN #####

source rmgr_setupenv

if [ "$1" = "-d" ]; then
    options="$1" && shift
else
    options=""
fi

[ -z "$1" ] && PrintUsage && exit 1

for file in "$@"; do
    rmgr_add "$file" "$options"
done
