#!/bin/sh

# Format the BibTeX record

PrintUsage() {
    cat << EOF
Usage: $(basename $0) <bibtex>

Format a BibTeX entry which includes the following steps:
- key is lowercase
- key contains dashes instead of underscores
- every line starts with two spaces

The result is left on stdout.
EOF
}

record="$1"
if [ -z "$record" ]; then
    [ ! -t 0 ] && record=$(</dev/stdin)
    [ -z "$record" ] && PrintUsage && exit 1
fi

# Make sure everything in the first line is lowercase
echo "$record" | head -n 1 | tr '[:upper:]' '[:lower:]' | tr '_' '-'
# Make every line start with two spaces
echo "$record" | tail -n +2 | sed -E 's/^\s+/  /'
