#!/bin/sh

# Update a specific dict value for a key

PrintUsage() {
    cat << EOF
Usage: $(basename $0) <bibkey> <datakey> <val>

Update a specific datakey value for a specific bibkey.
EOF
}

##### MAIN #####

source rmgr_setupenv

key="$1"
[ -z "$key" ] && PrintUsage && exit 1
datakey="$2"
[ -z "$datakey" ] && PrintUsage && exit 1
val="$3"
[ -z "$val" ] && PrintUsage && exit 1

# Verify that the record exists
searchResults=$(rmgr_lookupkey "$key")
case $? in
    0) ;;
    1) echo "Key $key not found." && exit 1 ;;
    2)
        echo "Multiple keys found matching $key:"
        rmgr_key2bib "$key"
        exit 2
        ;;
    *) echo "Unknown exit code recieved from rmgr_lookupkey." && exit 70
esac

# Check if the key exists
searchResults=$(sed -n "/^- $key:/,/^- / p" "$EXT" | grep "^  - $datakey:")
[ -z "$searchResults" ] && echo "Datakey $datakey not found." && exit 3

sed -i "/^- $key/,/^- / s/$datakey:.*$/$datakey: $val/" "$EXT"
