#!/bin/sh

# Add a file corresponding to a database entry

PrintUsage() {
    cat << EOF
Usage: $(basename $0) [<options>] <bibkey> <file>

Copy the file corresponding to a BibTeX entry into the appropriate directory.

Options:
  -d : delete the original file after copying
EOF
}

##### MAIN #####

source rmgr_setupenv

if [ "$1" = "-d" ]; then
    delete="yes"
    shift
else
    delete="no"
fi

key="$1"
[ -z "$key" ] && PrintUsage && exit 1
file="$2"
[ ! -f "$file" ] && PrintUsage && exit 1

searchResults=$(rmgr_lookupkey "$key")
case $? in
    0) ;;
    1) echo "Key $key not found." && exit 1 ;;
    2)
        echo "Multiple keys found matching $key:"
        rmgr_key2bib "$key"
        exit 2
        ;;
    *) echo "Unknown exit code received from rmgr_lookupkey." && exit 70
esac

case $(rmgr_key2bib "$key" | bib2type) in
    "article") dest="$ARTICLES" ;;
    "inproceedings") dest="$ARTICLES" ;;
    "book") dest="$BOOKS" ;;
    "techreport") dest="$TECHREPORTS" ;;
    "phdthesis") dest="$THESES" ;;
    *) echo No destination set for type $(rmgr_key2bib "$key" | bib2type). && exit 80
esac
if [ ! -d "$dest" ]; then
    if  ! mkdir -p "$dest"; then
        echo "Error creating $dest."
        exit 11
    fi
fi

newFilename=$(echo "$key" | tr '-' '_')
extension=${file##*.}
dest="$dest/$newFilename.$extension"
if [ -f "$dest" ]; then
    while true; do
        read -p "Destination ($dest) already exists. Still copy? [y|q]: " confirmation
        case "$confirmation" in
            "y") break ;;
            "q") exit 12 ;;
        esac
    done
else
    confirmation="y"
fi

if [ "$confirmation" = "y" ]; then
    read -p 'Enter reading folder (or leave empty): ' readingFolder
    # Copy the file
    cp -f "$file" "$dest"
    # Update the appropriate db fields
    rmgr_updval "$key" "date_updated" "$(date "+%Y-%m-%d %H:%M:%S %Z %:::z")"
    rmgr_updval "$key" "read_status" "unread"
    [ ! -z "$readingFolder" ] && rmgr_updval "$key" "reading_folder" "$readingFolder"
    [ "$delete" = "yes" ] && rm "$file"
fi

exit 0
