#!/bin/sh

# Add a file to the database (with unknown database entry)

PrintUsage() {
    cat << EOF
Usage: $(basename $0) [<options>] <file>

Add a file to the database regardless of whether or not a record for it already
exists in the database. This script helps to add the correct bibliographic
information.

Options:
  -d : delete the original file after copying
EOF
}

##### MAIN #####

source rmgr_setupenv

# [ "$1" = "-d" ] && { options="-d" ; shift } || options=""

if [ "$1" = '-d' ]; then
    options='-d'
    shift
else
    options=""
fi

file="$1"
[ ! -f "$file" ] && PrintUsage && exit 1

# Open the reader so the user can confirm
$READER "$file" &
previewPID="$!"

EndSafely() {
    kill "$previewPID"
    [ -z "$1" ] && exit 100 || exit "$1"
}

trap "EndSafely" SIGINT

# Try to infer DOI
doi=$(pdf2doi "$file")
[ -z "$doi" ] &&\
    read -p 'Autodetect failed. Search: ' searchTerms &&\
    doi=$(querycr "$searchTerms")

bibtex=$(doi2bib "$doi") || EndSafely "$?"

# Set the key based on some predefined format
bibtex=$(rmgr_formatkey "$bibtex") || EndSafely "$?"

# Add the entry
rmgr_addentry "$bibtex"
if [ $? = 50 ]; then
    echo "Entry addition skipped."
else
    EndSafely "$?"
    echo "Added entry."
fi

# Add the file
key=$(bib2key "$bibtex")
if [ -z "$options" ]; then
    rmgr_addfile "$key" "$file" || EndSafely "$?"
else
    rmgr_addfile "$options" "$key" "$file" || EndSafely "$?"
fi
echo "Added file."

EndSafely 0
