#!/bin/sh

# Get the EXT data entry for a key.
# If the key exists multiple times, show all EXT entries and exit.

PrintUsage() {
    cat << EOF
Usage: $(basename $0) <key>

Take a key and do a database lookup. Return all matching EXT data entries.

The key can be provided as an argument or via stdin. Command line arguments
take precedence over data piped in.

Exit Codes:
- 0 : success
- 1 : key not found (either in $$BIB or $$EXT)
- 2 : key found multiple times (either in $$BIB or $$EXT)
EOF
}

source rmgr_setupenv

key="$1"
if [ -z "$key" ]; then
    [ ! -t 0 ] && key=$(</dev/stdin)
    [ -z "$key" ] && PrintUsage && exit 1
fi

searchResults=$(rmgr_lookupkey "$key")
case $? in
    0) ;;
    1) echo "$key not found in $BIB" && exit 1 ;;
    2)
        echo "$key found multiple times in $BIB:"
        rmgr_key2bib "$key"
        exit 2
        ;;
esac

extdata=$(awk "/^-\s*$key:\s*$/ {flag=1} /^\s*$/ {flag=0} {if(flag) print}" "$EXT")
[ -z "$extdata" ] && exit 1
numRecords=$(echo "$extdata" | grep -E "^-" | wc -l)
echo "$extdata"
[ $numRecords -gt 1 ] && exit 2
exit 0
