#!/bin/sh

# Lookup a bib key in reflist.bib
# If the key is not found, return the empty string.
# If the key is already found, return all keys that start with it.

source rmgr_setupenv

# Read record from pipe (stdin) or argument
if (( $# == 0 )); then
    bibkey=$(</dev/stdin)
else
    bibkey="$1"
fi
[ -z "$bibkey" ] && exit 1

results=$(grep -E "^@.+{\s*$bibkey.*," "$BIB")
#[ -z "$results" ] || grep -E "^@.+{\s*$bibkey.*," "$BIB"
[ ! -z "$results" ] && awk "/^@.+{\s*$bibkey.*,/{flag=1}/^\s*}/{if(flag) print;flag=0}flag" "$BIB" || exit 2
