#!/bin/sh

# Get the BibTeX entry for a key.
# If the key exists multiple times, show all bibtex entries and exit.

PrintUsage() {
    cat << EOF
Usage: $(basename $0) <key>

Take a key and do a database lookup. Return all matching BibTeX entries.

The key can be provided as an argument or via stdin. Command line arguments
take precedence over data piped in.

Exit Codes:
- 0 : success
- 1 : key not found
- 2 : key found multiple times
EOF
}

source rmgr_setupenv

key="$1"
if [ -z "$key" ]; then
    [ ! -t 0 ] && key=$(</dev/stdin)
    [ -z "$key" ] && PrintUsage && exit 1
fi

bibtex=$(awk "/^@.+\{\s*$key\s*,/ {flag=1} /^\s*\}/ {if(flag) print; flag=0} flag" "$BIB")
[ -z "$bibtex" ] && exit 1
numBibs=$(echo "$bibtex" | grep -E "^@.+\{" | wc -l)
echo "$bibtex"
[ $numBibs -gt 1 ] && exit 2
exit 0
