#!/bin/sh

# Setup the environment
RMGRCONFDIR="$XDG_CONFIG_HOME/rmgr"
[ ! -d "$RMGRCONFDIR" ] && echo "Config directory missing." && exit 99

export RMGRCONFDIR

RMGRCONF="$RMGRCONFDIR/rmgr.conf"

[ ! -f "$RMGRCONF" ] && echo "Config missing." && exit 99

source "$RMGRCONF"
