#!/bin/sh

# Read the file corresponding to a bibkey.

PrintUsage() {
    cat << EOF
Usage: $(basename $0) <key>

Open a file corresponding to a bibkey.
EOF
}

##### MAIN #####

source rmgr_setupenv

key="$1"
[ -z "$key" ] && PrintUsage && exit 1

searchResults=$(rmgr_lookupkey "$key")
case $? in
    0)
        type=$(rmgr_key2bib "$searchResults" | bib2type)
        case "$type" in
            article) dir="$ARTICLES" ;;
            book) dir="$BOOKS" ;;
            phdthesis) dir="$THESES" ;;
            techreport) dir="$TECHREPORTS" ;;
            *) echo "Unknown directory for $type." && exit 10 ;;
        esac
        filename="$(sed 's/-/_/g' <<< $searchResults).pdf"
        $READER "$dir/$filename" ;;
    1) echo "$key not found in $BIB" && exit 1 ;;
    2)
        echo "$key found multiple times:"
        rmgr_key2bib "$key"
        exit 2
        ;;
esac
