#!/bin/sh

# Find the BibTeX entry for a bibkey

PrintUsage() {
    cat 1>&2 << EOF
Usage: $(basename $0) <bibkey>

Extract the BibTeX record corresponding to a bibkey.
EOF
}

##### MAIN #####

source rmgr_setupenv

key="$1"
[ -z "$key" ] && echo "$key not found." && exit 1

sed -n "/@.*{\s*$key/,/^\s*}/ p" "$BIB"
