#!/bin/sh

# Document config
RMGR_ROOT="/media/anantg/schonbrunn/reading"
ARTICLES="$RMGR_ROOT/articles"
BOOKS="$RMGR_ROOT/books"
THESES="$RMGR_ROOT/theses"

# Notes config
NOTES="/home/anantg/dev/rfdg/lit"
TEMPLATES="$NOTES/templates"
EXTENSION="md"

# Database files
BIB="$NOTES/reflist2.bib"
EXT="$NOTES/ext.yaml"

# Key format
# Example: "%a1f%a1L-%Y"
# Use the following codes for the key:
# - a1f: Author 1's first initial
# - a1L: Author 1's last name
# - Y  : Year
# KEY_FORMAT="%a1f%a1L-%Y"
