#!/bin/sh

# Document config
RMGR_ROOT="$XDG_DATA_HOME/rmgr"
DOCS_ROOT="$RMGR_ROOT/docs"
ARTICLES="$DOCS_ROOT/articles"
BOOKS="$DOCS_ROOT/books"
TECHREPORTS="$DOCS_ROOT/techreports"
THESES="$DOCS_ROOT/theses"

# Notes config
NOTES="$XDG_DATA_HOME/rmgr/notes"
TEMPLATES="$NOTES/templates"
EXTENSION="md"

# Database files
BIB="$NOTES/reflist.bib"
EXT="$NOTES/ext.yaml"
