#!/bin/sh

# Get the BibJSON entry for a DOI number.

PrintUsage() {
  cat << EOF
Usage: $(basename $0) <doi>

Query the crossref API to get the BibJSON entry corresponding to the given DOI.

The DOI can be provided as an argument or via stdin. Command line arguments
take precendence over data piped in.
EOF
}

doi="$1"
if [ -z "$doi" ]; then
  [ ! -t 0 ] && doi=$(</dev/stdin)
  [ -z "$doi" ] && PrintUsage && exit 1
fi

curl -s "http://api.crossref.org/works/$doi" | jq -r '.message'
