#!/bin/sh

[ "$1" = "-f" ] && filterFile="$2" || regex="$1"

[ ! -z "$filterFile" ] && [ ! -f "$filterFile" ] && exit 1

if [ ! -z "$filterFile" ]; then
  regex=$(cat "$filterFile" | sed -E 's/$/|/' | tr -d '\n' | sed 's/|$//')
fi

cat /dev/stdin |\
  grep -v '^\s*$' |\
  sed -E 's/$/~~/' |\
  sed -E 's/^-/~~~-/' |\
  sed -E 's/^  -/~~~  -/' |\
  tr -d '\n' |\
  sed 's/~~~~~/~~\n/g' |\
  sed -E 's/^~~~-/-/' |\
  grep -E "^-|^  - ($regex)" |\
  sed -E 's/~~$//'
