#!/bin/sh

# Preview a summary file

SplitAndPreview() {
  sed -n '/^---$/,/^...$/p' "$1" | $BAT_YAML
  sed '/^---$/,/^...$/d' "$1" | $BAT_MD
}

SearchSplitAndPreview() {
  sed -n '/^---$/,/^...$/p' "$1" \
    | grep --ignore-case --color=always -E "$2|$" \
    | $BAT_YAML
  sed '/^---$/,/^...$/d' "$1" \
    | grep --ignore-case --color=always -E "$2|$" \
    | $BAT_MD
}

##### MAIN #####

path="$1"
argType="$2"
searchTerm="$3"

case "$argType" in
  "full_ripgrep") path=$(echo "$path" | cut -d ':' -f 1) ;;
  *) ;;
esac

[ ! -f "$path" ] && echo "$path is not a file" && exit 1

[ -z "$searchTerm" ] \
  && SplitAndPreview "$path" \
  || SearchSplitAndPreview "$path" "$searchTerm"
