#!/bin/sh

# Edit the note associated with a key

PrintUsage() {
  cat << EOF
Usage: $(basename $0) <key>

Open the note that matches a specific key in an editor.

The key can be piped in or provided as an argument (takes precedence).

Error codes:
- 0: success
- 1: insufficient arguments
EOF
}

##### MAIN #####

key="$1"
if [ -z "$key" ]; then
  [ ! -t 0 ] && key=$(</dev/stdin)
  [ -z "$key" ] && PrintUsage && exit 1
fi

# Get the type of record
entryType=$(key2record "$key" | getyamlval 'type')

# Create the filepath
filename=$(echo "$key" | sed 's/-/_/').txt
filepath="$NOTES/$entryType/$filename"

# If the directory does not exist, create it
dir=$(dirname "$filepath")
[ ! -d "$dir" ] && mkdir -p "$dir"

$EDITOR "$filepath"
